// Generated by DPM -> github.com/dpmland
//
// This file is automaticall generated by dpm if you want modify manual can be write!
//
// DEPS SYNTAX:
// export * as MODULENAME from 'HOST_URL/MODULE_NAME@VERSION_AUTOMATICALL/FILE_MOD'
//
// DEPENDENCY LIST ...
