import { ReadDpmFile } from 'dpm/read.ts';
import { BASE_DIRECTORIES, NAME_DIRECTORIES } from 'mods/dirs.ts';
import { LOGGER } from 'mods/logger.ts';
import { ask } from 'mods/ask.ts';

export async function generateEggsFile() {
  const data = await ReadDpmFile();
  const file = `
{
  "name": "${data.name}",
  "entry": "${data.main}",
  "description": "${data.description}",
  "version": "${data.version}",
  "homepage": "https://github.com/your_name/${data.name}",
  "unstable": true,
  "unlisted": false,
  "version": "0.0.1",
  "releaseType": "patch",
  "files": ["./mod.ts", "./src/**/*", "./README.md"],
  "ignore": [".git"],
  "checkFormat": "deno fmt",
  "checkTests": "deno test",
  "checkInstallation": true,
  "check": false
}
  `;
  console.log(`File generated by DPM...`);
  console.log(JSON.stringify(JSON.parse(file), null, '  '));
  const answers = await ask.prompt([
    {
      name: 'write',
      message: 'Do you want write the file with this data',
      type: 'confirm',
    },
  ]);
  if (answers.write) {
    await Deno.writeTextFile(BASE_DIRECTORIES.EGGS_FILE, file);
    LOGGER.info(`Writed successfully the ${NAME_DIRECTORIES.EGGS_FILE}`);
  }
}
